server:
  port: 8080
  
spring:
  jpa:
    hibernate:
      ddl-auto: update

  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Cards
    username: postgres
    password: lalo
    continueOnError: true
    
variables:
  keys: 100,110,300,400,500,600,800,900,950
varia:
  arre: 0,1
iterator:
  fin: 300000
